# Generated by Django 5.2.8 on 2026-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order_type', models.CharField(max_length=255, verbose_name='Вид заказа')),
                ('order_details', models.TextField(verbose_name='Данные заказа')),
                ('extra_info', models.TextField(blank=True, verbose_name='Дополнительные данные')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата')),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предоплата')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Остаток')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('progress', 'В работе'), ('ready', 'Готов'), ('done', 'Выдан')], default='new', max_length=20, verbose_name='Готовность заказа')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частично'), ('paid', 'Оплачено')], default='unpaid', max_length=20)),
            ],
        ),
    ]
