# Generated by Django 5.2.8 on 2026-05-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частично'), ('paid', 'Оплачено')], default='unpaid', max_length=20),
        ),
    ]
