# Generated by Django 5.2.8 on 2026-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частично'), ('paid', 'Оплачено')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('progress', 'В работе'), ('ready', 'Готов'), ('done', 'Выдан'), ('cancel', 'Отменено')], default='new', max_length=20, verbose_name='Готовность заказа'),
        ),
    ]
